import { ruleset } from '../src/engine/rules.js';
import { spawn, spawnSync } from 'node:child_process';
import { createInterface } from 'node:readline';
import { readFileSync } from 'node:fs';
import { DISCLAIMER } from '../src/engine/common.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
test('MCP stdio lists tools, scans, returns errors and remains usable', {timeout:15000},async t=>{
  const client=new Client({name:'reinhardt-test',version:'1.0.0'});
  const transport=new StdioClientTransport({command:process.execPath,args:[fileURLToPath(new URL('../bin/reinhardt.js',import.meta.url)),'mcp'],stderr:'pipe'});
  t.after(()=>client.close());
  await client.connect(transport);
  const {tools}=await client.listTools();
  assert.deepEqual(tools.map(tool=>tool.name).sort(),['drift_check','explain_sdk','list_rules','owasp_lookup','save_baseline','scan_repo']);
  assert.match(tools.find(tool=>tool.name==='save_baseline').description,/only after the user accepted/);
  const result=await client.callTool({name:'scan_repo',arguments:{path:fileURLToPath(new URL('../evals/fixtures/leaky-web',import.meta.url))}});
  assert.ok(!result.isError);
  assert.ok(JSON.parse(result.content[0].text).findings.some(f=>f.id==='undisclosed-sdk'));
  const failure=await client.callTool({name:'scan_repo',arguments:{path:'/nonexistent-reinhardt-fixture'}});
  assert.equal(failure.isError,true);
  assert.match(failure.content[0].text,/not legal advice/);
  const invalid=await client.callTool({name:'scan_repo',arguments:{path:123}});
  assert.equal(invalid.isError,true);
  const knowledge=await client.callTool({name:'owasp_lookup',arguments:{query:'LLM10:2026'}});
  assert.equal(knowledge.structuredContent.results[0].item.name,'Improper Output Handling');
  const rules=await client.callTool({name:'list_rules',arguments:{}});
  assert.equal(rules.structuredContent.rules.length,ruleset.rules.length);
  const security=await client.callTool({name:'scan_repo',arguments:{path:fileURLToPath(new URL('../evals/fixtures/leaky-security-web',import.meta.url))}});
  assert.equal(JSON.stringify(security).includes('AKIA'+'IOSFODNN7EXAMPLE'),false);
  for (const tool of tools) assert.ok(tool.description.endsWith(DISCLAIMER));
  const healthy=await client.callTool({name:'explain_sdk',arguments:{id:'posthog'}});
  assert.equal(JSON.parse(healthy.content[0].text).sdks[0].id,'posthog');
});
test('raw MCP protocol errors, notifications and recovery', {timeout:10000}, async t => {
  const child = spawn(process.execPath,['bin/reinhardt.js','mcp'],{stdio:['pipe','pipe','pipe']});
  t.after(()=>child.kill());
  const lines = createInterface({input:child.stdout});
  const output = lines[Symbol.asyncIterator]();
  const send = message => child.stdin.write((typeof message === 'string' ? message : JSON.stringify(message))+'\n');
  const next = async () => JSON.parse((await output.next()).value);
  send('{broken');
  assert.equal((await next()).error.code,-32700);
  send({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'raw',version:'1'}}});
  const initialization = (await next()).result;
  assert.equal(initialization.protocolVersion,'2025-03-26');
  assert.equal(initialization.serverInfo.version,'0.2.0');
  send({jsonrpc:'2.0',method:'notifications/initialized'});
  send({jsonrpc:'2.0',method:'notifications/anything'});
  send({jsonrpc:'2.0',id:2,method:'ping'});
  assert.deepEqual(await next(),{jsonrpc:'2.0',id:2,result:{}});
  send({jsonrpc:'2.0',id:3,method:'unknown'});
  assert.equal((await next()).error.code,-32601);
  send({jsonrpc:'2.0',id:4,method:'tools/call',params:{}});
  assert.equal((await next()).error.code,-32602);
  send({jsonrpc:'2.0',id:5,method:'tools/list'});
  assert.equal((await next()).result.tools.length,6);
  send({jsonrpc:'2.0',id:6,method:'tools/call',params:{name:'scan_repo',arguments:{path:'/does-not-exist-reinhardt'}}});
  const failure=await next();
  assert.equal(failure.result.isError,true);
  assert.equal(JSON.stringify(failure).includes('/does-not-exist-reinhardt'),false);
});
test('MCP runtime has no package dependencies and can start without imports from node_modules', () => {
  const manifest=JSON.parse(readFileSync(new URL('../package.json',import.meta.url)));
  assert.equal(Object.keys(manifest.dependencies ?? {}).length,0);
  assert.ok(manifest.devDependencies['@modelcontextprotocol/sdk']);
  assert.equal(manifest.devDependencies.zod,undefined);
  const result=spawnSync(process.execPath,['--input-type=module','-e',`import { register } from 'node:module'; register('data:text/javascript,'+encodeURIComponent('export async function resolve(specifier, context, next) { if (!specifier.startsWith("node:") && !specifier.startsWith(".") && !specifier.startsWith("file:")) throw new Error("External dependency blocked"); return next(specifier, context); }'), import.meta.url); await import('./src/mcp.js');`],{encoding:'utf8'});
  assert.equal(result.status,0,'MCP imported a runtime package');
});
